# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUU5miaABkQ1dVHuFia-NXtXbwx19KVn
"""

import streamlit as st
<<<<<<< HEAD:app.py
import os
input_firstname = st.text_input('名前を入力してください:')
input_lastname = st.text_input('名字を入力してください:')
st.write('生年月日を入力してください:"')
cols = st.columns(3)
year = cols[0].text.input('年',placeholder = 'yyyy')
month = cols[1].text.input('月',placeholder = 'mm')
day = cols[2].text.input('日',placeholder = 'dd')
if year and month and day:
  st.success(f"{year}年{month}月{day}日")
=======
import itertools
l0 = ['', '']                   #名前の文字列
l1=["none","upper"]             # 何もしない、大文字へ
l2=["all","first","even","odd"] # 全部、最初だけ、偶数番目だけ、奇数番目だけ

n0 = ['', '', '']               #誕生日の文字列

s0=["!", "#", "$", "%", "=", "-", "+", "@"] #記号の文字列

l0[0] = st.input('名前を入力してください:')
l0[1] = st.input('名字を入力してください')
n0[0] = st.input('生まれた年を入力してください:')
n0[1] = st.input('生まれた月を入力してください:')
n0[2] = st.input('生まれた日付を入力してください:')

c0=["010", "012", "013", "014",
    "020", "021", "023", "024",
    "030", "031", "032", "034",
    "040", "041", "042", "043",
    "101", "102", "103", "104",
    "120", "121", "123", "124",
    "130", "131", "132", "134",
    "140", "141", "142", "143",
    "201", "202", "203", "204",
    "210", "212", "213", "214",
    "230", "231", "232", "234",
    "240", "241", "242", "243",
    "301", "302", "303", "304",
    "310", "312", "313", "314",
    "320", "321", "323", "324",
    "340", "341", "342", "343",
    "401", "402", "403", "404",
    "410", "412", "413", "414",
    "420", "421", "423", "424",
    "430", "431", "432", "434"] #　並びパターン

def change0(x0,x1,x2): # 文字列の置き換え
  if x1=="none":
    return x0
  elif x1=="upper":
    if x2=="all":
      return x0.upper()
    elif x2=="first":
      return x0[0].upper()+x0[1:]
    elif x2=="even":
      return "".join([x0[i].upper() if i%2==0 else x0[i] for i in range(len(x0))])
    elif x2=="odd":
      return "".join([x0[i].upper() if i%2==1 else x0[i] for i in range(len(x0))])
    else:
      return x0
  else:
    return x0

def change1(x0,x1,cc): # 文字列の置き換え
  x=""
  for i in range(len(cc)):
    if cc[i]=="0":
      x=x+x0[0]
    elif cc[i]=="1":
      x=x+x0[1]
    elif cc[i]=="2":
      x=x+x1[0]
    elif cc[i]=="3":
      x=x+x1[1]
    elif cc[i]=="4":
      x=x+x1[2]
    else:
      x=x
  return x

count=0
for v1,v2,w0 in itertools.product(l1,l2,c0):
  #print(v0,v1,v2)
  name=[]
  name.append(change0(l0[0],v1,v2))
  name.append(change0(l0[1],v1,v2))
  x=change1(name,n0,w0)
  st.print(x)
  count+=1

st.print("Total= ",count)
>>>>>>> 23e40217ddbdc5fee0fbe4c5332173424abc201f:パスワード自動生成プログラム(先生ベース).py
