# -*- coding: utf-8 -*-
"""パスワード自動生成プログラム(先生ベース).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAebmKC6sCd9nUPyu5oh9DZWN2GmlPDm
"""

import itertools
l0=['myoji','namae']      # 元の名前の文字列
l1=["none","upper"]             # 何もしない、大文字へ
l2=["all","first","even","odd"] # 全部、最初だけ、偶数番目だけ、奇数番目だけ

n0=["123","456","789"]             # 誕生日をもとにした文字列

s0=["!", "#", "$", "%", "=", "-", "+", "@"] #記号の文字列

c0=["0","1","01","10","02","03","04","12","13","14","20","30","40","21","31","41","53"] #　並びパターン

def change0(x0,x1,x2): # 文字列の置き換え
  if x1=="none":
    return x0
  elif x1=="upper":
    if x2=="all":
      return x0.upper()
    elif x2=="first":
      return x0[0].upper()+x0[1:]
    elif x2=="even":
      return "".join([x0[i].upper() if i%2==0 else x0[i] for i in range(len(x0))])
    elif x2=="odd":
      return "".join([x0[i].upper() if i%2==1 else x0[i] for i in range(len(x0))])
    else:
      return x0
  else:
    return x0

def change1(x0,x1,cc): # 文字列の置き換え
  x=""
  for i in range(len(cc)):
    if cc[i]=="0":
      x=x+x0[0]
    elif cc[i]=="1":
      x=x+x0[1]
    elif cc[i]=="2":
      x=x+x1[0]
    elif cc[i]=="3":
      x=x+x1[1]
    elif cc[i]=="4":
      x=x+x1[2]
    else:
      x=x
  return x

count=0
for v1,v2,w0 in itertools.product(l1,l2,c0):
  #print(v0,v1,v2)
  name=[]
  name.append(change0(l0[0],v1,v2))
  name.append(change0(l0[1],v1,v2))
  x=change1(name,n0,w0)
  print(x)
  count+=1

print("Total= ",count)
