# -*- coding: utf-8 -*-
"""パスワード自動生成プログラム.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtXMt0nR1qV6KcKpf0rJUQ3Cqt533qb8
"""

import random, string
num = int(input('何文字のパスワードを生成しますか:'))
a = input('好きな文字列を入力してください: ')
if len(a) > num:
    print('入力できる文字数を超えています')
elif len(a) == num:
    print('生成したい文字数と入力した文字数が一致しています')
    print(a)
else:
    b = random.randint (0, num - len(a))
    def randomname(b):
       randlst = [random.choice(string.ascii_letters + string.digits) for i in range(b)]
       return ''.join(randlst)
    c = num - (len(a) + b)
    def randomname(c):
       randlst = [random.choice(string.ascii_letters + string.digits) for i in range(c)]
       return ''.join(randlst)
    print('パスワードを生成しました')
    print(randomname(b)+a+randomname(c))